name: isca_docs
channels:
- conda-forge
dependencies:
- dask
- f90nml
- fortran-compiler
- ipykernel
- jinja2
- libgfortran
- netcdf-fortran
- nbsphinx
- numpy
- openmpi
- pandas
- python=3.9
- pip
- pytest
- sh
- sphinx
- sphinx_rtd_theme
- tqdm
- xarray
